=head1 NAME

App::wwwbench -

=head1 SYNOPSIS

  use App::wwwbench;

=head1 DESCRIPTION

App::wwwbench is

=head1 AUTHOR

Kenta Sato E<lt>karupa@cpan.orgE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

